$ErrorActionPreference="Continue"
Write-Host "-------- broad search for CK_v23 report files --------"
$hits=Get-ChildItem "C:\Users\prita" -Recurse -Filter "CK_v23_*" -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in ".htm",".html",".xml" }
if($hits){ $hits | ForEach-Object { Write-Host ("  FOUND: " + $_.FullName) } } else { Write-Host "  no html/xml report anywhere (report not generated by this build)" }
Write-Host ""
Write-Host "-------- final balance + trade count from tester logs --------"
$logs=Get-ChildItem "C:\Users\prita\AppData\Roaming\MetaQuotes" -Recurse -Include *.log -ErrorAction SilentlyContinue | Where-Object { $_.FullName -match "logs" } | Sort-Object LastWriteTime -Descending | Select-Object -First 8
foreach($l in $logs){
  $b=[IO.File]::ReadAllBytes($l.FullName)
  if(($b[0..([Math]::Min(2000,$b.Length-1))] -contains 0)){ $t=[Text.Encoding]::Unicode.GetString($b) } else { $t=[Text.Encoding]::UTF8.GetString($b) }
  $fb=[regex]::Matches($t,'final balance ([\d\. ]+) USD')
  $deals=[regex]::Matches($t,'deal #\d+ (buy|sell)').Count
  $sl=[regex]::Matches($t,'stop loss triggered').Count
  $tp=[regex]::Matches($t,'take profit triggered').Count
  if($fb.Count -gt 0 -or $deals -gt 0){
    $bals=($fb | ForEach-Object { $_.Groups[1].Value.Trim() }) -join ', '
    Write-Host ("  " + $l.FullName)
    Write-Host ("     final balance(s): " + $bals + "   dealLines=" + $deals + "  SLhits=" + $sl + "  TPhits=" + $tp)
  }
}
Write-Host "== DIAG3 END =="
